### ISSUE TITLE
Build issue on Linux (Monodevelop)

### ISSUE THREAD

**Issue by sum01** [Equilibrium-Games/Acid-Editor#3]
I get an `Invalid Resx file. XOR data length expected 2046820352, read 276` error [here](https://github.com/Equilibrium-Games/Acid-Editor/blob/65c7d709f7c9b63ad04642fe2e96f62fa3273c2a/Acid.Editor/Forms/Dialogs/DialogFont.resx#L121-L129), [here](https://github.com/Equilibrium-Games/Acid-Editor/blob/65c7d709f7c9b63ad04642fe2e96f62fa3273c2a/Acid.Editor/Forms/Dialogs/DialogAbout.resx#L121-L130), and [here](https://github.com/Equilibrium-Games/Acid-Editor/blob/65c7d709f7c9b63ad04642fe2e96f62fa3273c2a/Acid.Editor/Forms/Dialogs/DialogSettings.resx#L121-L130) (with minor differences in the read number)

I don't know anything about C#, so I'm pretty clueless as to how to fix it.

**Comment by mattparks** [comment]
The editor can compile with those three data section removed. Currently on Linux Acid# calls will result in a crash, without any Acid calls the editor opens and displays fine. Acid Sharp will require a few changes to allow for it to run properly on Linux.

**Comment by sum01** [comment]
That did fix the build issue.

It fails in [Main()](https://github.com/Equilibrium-Games/Acid-Editor/blob/master/Acid.Editor/Program.cs#L13). I assume this is related to Acid.Sharp as you mentioned.
